[controls.axes.Player]
mouse_axis.axis = 0

# [controls.axes.Player]
# emulated.neg.key = "Left"
# emulated.pos.key = "Right"

[controls.actions.Shoot]
combinations = [[{ mouse_button = "MouseButtonLeft" }], [{ key = "Z" }]]

[controls.actions.EnableDisableSound]
combinations = [[{ key = "M" }]]
once = true


# Usage

# Axes

# With keyboard keys
# [controls.axes.XXX]
# emulated.neg.key = "Left"
# emulated.pos.key = "Right"

# With mouse buttons
# [controls.axes.XXX]
# emulated.neg.mouse_button = "MouseButtonLeft"
# emulated.pos.mouse_button = "MouseButtonRight"

# With gamepad buttons
# [controls.axes.XXX]
# emulated.neg.controller = { id = 0, button = "GamepadButton14" }
# emulated.pos.controller = { id = 0, button = "GamepadButton15" }

# With gamepad axis
# [controls.axes.XXX]
# controller_axis = { id = 0, axis = 0, invert = false, dead_zone = 0.2 }

# With mouse axis
# [controls.axes.XXX]
# mouse_axis.axis = 0


# Actions

# [controls.actions.XXX]
# combinations = [
#     [{ key = "ControlLeft" }, { key = "Q" }],
#     [{ key = "Escape" }],
#     [{ controller = { id = 0, button = "GamepadButton9" } }],
# ]
# once = true
