[[entity]]

    [entity.components.Text]
    id = "game_difficulty"
    text = "NORMAL"
    font_face = { font = "joystix", options = { size = 25.0, hinting = "Full" } }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 500, y = 790 }
    pivot = "TopMiddle"
