[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 95.0, y = 400.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 185.0, y = 400.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 275.0, y = 400.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 365.0, y = 400.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 455.0, y = 400.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 545.0, y = 400.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 635.0, y = 400.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 725.0, y = 400.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 815.0, y = 400.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 905.0, y = 400.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }


[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 95.0, y = 472.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 185.0, y = 472.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 275.0, y = 472.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 365.0, y = 472.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 455.0, y = 472.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 545.0, y = 472.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 635.0, y = 472.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 725.0, y = 472.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 815.0, y = 472.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }
Transform = { translation = { x = 905.0, y = 472.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_1", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 72.0, height = 48.0 }


[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 95.0, y = 544.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 185.0, y = 544.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 275.0, y = 544.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 365.0, y = 544.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 455.0, y = 544.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 545.0, y = 544.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 635.0, y = 544.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 725.0, y = 544.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 815.0, y = 544.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 905.0, y = 544.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }


[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 95.0, y = 616.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 185.0, y = 616.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 275.0, y = 616.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 365.0, y = 616.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 455.0, y = 616.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 545.0, y = 616.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 635.0, y = 616.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 725.0, y = 616.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 815.0, y = 616.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }
Transform = { translation = { x = 905.0, y = 616.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_2", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 66.0, height = 48.0 }


[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 6 }
Transform = { translation = { x = 95.0, y = 688.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_3", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 48.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 6 }
Transform = { translation = { x = 185.0, y = 688.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_3", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 48.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 6 }
Transform = { translation = { x = 275.0, y = 688.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_3", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 48.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 6 }
Transform = { translation = { x = 365.0, y = 688.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_3", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 48.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 6 }
Transform = { translation = { x = 455.0, y = 688.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_3", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 48.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 6 }
Transform = { translation = { x = 545.0, y = 688.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_3", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 48.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 6 }
Transform = { translation = { x = 635.0, y = 688.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_3", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 48.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 6 }
Transform = { translation = { x = 725.0, y = 688.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_3", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 48.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 6 }
Transform = { translation = { x = 815.0, y = 688.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_3", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 48.0, height = 48.0 }

[[entity]]
[entity.components]
SpriteRender = { sprite_sheet_name = "game", sprite_number = 6 }
Transform = { translation = { x = 905.0, y = 688.0 } }
AnimationControl = { sprite_sheet_name = "game", animation_name = "alien_loop_3", end = { type = "Loop" }, command = { type = "Start" }, rate_multiplier = 1.0 }
Enemy = {}
Alien = { width = 48.0, height = 48.0 }
