[[entity]]

[entity.components.SpriteRender]
sprite_sheet_name = "game"
sprite_number = 16

[entity.components.Transform]
translation = { x = 500.0, y = 30.0 }

[entity.components.Player]

[entity.components.Controllable]
width = 90.0
height = 48.0
